// login.js – Username / E‑mail login  (Firebase v11.7.1 modular)

import { initializeApp } from "https://www.gstatic.com/firebasejs/11.7.1/firebase-app.js";
import {
  getAuth,
  signInWithEmailAndPassword,
  setPersistence,
  browserLocalPersistence,
  onAuthStateChanged
} from "https://www.gstatic.com/firebasejs/11.7.1/firebase-auth.js";

/* ─────────────  CONFIGURE  ───────────── */
const firebaseConfig = {
  apiKey:            "AIzaSyBa6rufBv_LnOuPwWrDdDpwMua2n49Hczo",
  authDomain:        "bettingwebsite-6b685.firebaseapp.com",
  projectId:         "bettingwebsite-6b685",
  storageBucket:     "bettingwebsite-6b685.appspot.com",
  messagingSenderId: "44929634591",
  appId:             "1:44929634591:web:99d7604a031b4a4f99a02a",
  measurementId:     "G-3PLM5LFY6X"
};

/* If you rename your HTML files, change these two only ↓↓↓ */
const LOGGED_IN_PAGE  = "logged-1xcopy-beautified.html";
const LOGGED_OUT_PAGE = "1xcopy-beautified.html";

/* ─────────────  INITIALISE  ───────────── */
const app  = initializeApp(firebaseConfig);
const auth = getAuth(app);

/* Persist across reloads / restarts (same as auth.js) */
setPersistence(auth, browserLocalPersistence).catch(console.error);

document.addEventListener("DOMContentLoaded", () => {
  /* If the user is already signed in, skip the form entirely */
  onAuthStateChanged(auth, user => {
    if (user) window.location.replace(LOGGED_IN_PAGE);
  });

  /* ----- SELECT FORM CONTROLS ----- */
  const idInput  = document.querySelector("input.ui-field__input:not([type='password'])");
  const pwInput  = document.querySelector("input.ui-field__input[type='password']");
  const loginBtn = document.querySelector("button.auth-form-by-password__submit");

  if (!idInput || !pwInput || !loginBtn) {
    console.error("Login form elements not found. Check your selectors.");
    return;
  }

  /* ----- LOGIN HANDLER ----- */
  loginBtn.addEventListener("click", async (e) => {
    e.preventDefault();

    let idOrEmail = idInput.value.trim();
    const password = pwInput.value;

    if (!idOrEmail || !password) {
      return alert("Please enter both your email (or username) and password.");
    }

    /* Allow login by autogenerated username alone */
    if (!idOrEmail.includes("@")) idOrEmail += "@autogen.local";

    try {
      await signInWithEmailAndPassword(auth, idOrEmail, password);
      console.log("✅ Login successful:", idOrEmail);
      window.location.replace(LOGGED_IN_PAGE);
    } catch (err) {
      console.error("❌ Login failed:", err);
      alert("Login error: " + err.message);
    }
  });
});
