// login.js – Email/Username Login with Firebase Auth (Modular SDK v11.7.1)

import { initializeApp } from "https://www.gstatic.com/firebasejs/11.7.1/firebase-app.js";
import {
  getAuth,
  signInWithEmailAndPassword
} from "https://www.gstatic.com/firebasejs/11.7.1/firebase-auth.js";

// Your Firebase configuration (must match auth.js)
const firebaseConfig = {
  apiKey:             "AIzaSyBa6rufBv_LnOuPwWrDdDpwMua2n49Hczo",
  authDomain:         "bettingwebsite-6b685.firebaseapp.com",
  projectId:          "bettingwebsite-6b685",
  storageBucket:      "bettingwebsite-6b685.appspot.com",
  messagingSenderId:  "44929634591",
  appId:              "1:44929634591:web:99d7604a031b4a4f99a02a",
  measurementId:      "G-3PLM5LFY6X"
};

// Initialize Firebase
const app  = initializeApp(firebaseConfig);
const auth = getAuth(app);

console.log("✅ login.js loaded");

document.addEventListener("DOMContentLoaded", () => {
  // Select the login form elements by class
  const idInput   = document.querySelector("input.ui-field__input:not([type='password'])");
  const pwInput   = document.querySelector("input.ui-field__input[type='password']");
  const loginBtn  = document.querySelector("button.auth-form-by-password__submit");

  if (!idInput || !pwInput || !loginBtn) {
    console.error("Login form elements not found. Check your selectors.");
    return;
  }

  loginBtn.addEventListener("click", async (e) => {
    e.preventDefault();
    let idOrEmail = idInput.value.trim();
    const password = pwInput.value;

    if (!idOrEmail || !password) {
      alert("Please enter both your email (or username) and password.");
      return;
    }

    // If user provided only the autogenerated username, append its domain
    if (!idOrEmail.includes("@")) {
      idOrEmail += "@autogen.local";
    }

    try {
      await signInWithEmailAndPassword(auth, idOrEmail, password);
      console.log("✅ Login successful:", idOrEmail);
      // Redirect to your post-login page
      window.location.href = "dashboard.html";
    } catch (error) {
      console.error("❌ Login failed:", error);
      alert("Login error: " + error.message);
    }
  });
});
